exp_name: ft
n_gpu: 2
tensorboard: True
model_arch: b32
checkpoint_path: ../weights/pytorch/imagenet21k+imagenet2012_ViT-B_32.pth
reset_classifier: True
image_size: 384
batch_size: 80
num_workers: 4
train_steps: 20000
data_dir: ../data/lad
dataset: LadAttributes
hidden_layers_dim: []
num_classes: 359
classifier_activation: ReLU
attn_dropout_rate: 0.0
dropout_rate: 0.1
classifier_dropout_rate: 0.1
pos_weight: 10

optimizer:
  type: SGD
  parameters:
    lr: 0.03
    weight_decay: 0.0
    momentum: 0.9

lr_scheduler:
  type: OneCycleLR
  step_per_batch: True
  parameters:
    max_lr: 0.03
    pct_start: 0.05
    total_steps: 20000

