exp_name: ft
n_gpu: 1
tensorboard: False
model_arch: b32
checkpoint_path: /home/toni/velebitai_task/visual-transformer/weights/pytorch/imagenet21k+imagenet2012_ViT-B_32.pth
reset_classifier: True
image_size: 384
batch_size: 10
num_workers: 2
train_steps: 10000
data_dir: /home/toni/Downloads/lad
dataset: LadAttributes
hidden_layers_dim:
  - 500
  - 350
num_classes: 359
classifier_activation: ReLU
attn_dropout_rate: 0.3
dropout_rate: 0.3
classifier_dropout_rate: 0.1
pos_weight: 10.0

optimizer:
  type: SGD
  parameters:
    lr: 0.001
    weight_decay: 0.0
    momentum: 0.9

lr_scheduler:
  type: OneCycleLR
  step_per_batch: True
  parameters:
    max_lr: 0.001
    pct_start: 0.05
    total_steps: 10000

